version: "3.8"
services:
  web:
    build: ./web-react
    ports:
      - 3000:3000
    depends_on:
      - api
    environment:
      GRAPQL_API_URL: http://localhost:3001/graphql
  api:
    build: ./api
    ports:
      - 3001:3001
